HAP-2-LinkRegister --  Added city field to user. Updated Register.
radusalex1/HappyCamps-backend pull request #2
Opened 2023-03-09 20:37 UTC by radusalex1

2023-03-10 18:34 UTC, TinelValentin requested changes

2023-03-10 18:34 UTC, TinelValentin commented on Controllers/UserController.cs
> +        private User ToUser(UserRegisterDTO userRegisterDTO)
This function does not belong in a controller

2023-03-10 18:34 UTC, TinelValentin commented on Controllers/UserController.cs
> +        private Role SetRole(string roleFromFrontend)
as nice as it sounds role from frontend is not that good of a name, i suggest to change it to recivedName since an API can be called from another backend app

2023-03-10 18:34 UTC, TinelValentin commented on Controllers/UserController.cs
> +                default:
I don't recomend to let the organizer be a default role, If by a mistake we get a corrupted role we do not want to register it as an organizer, change it to volunteer or just a default break works

2023-03-10 18:34 UTC, TinelValentin commented on DTOs/UserRegisterDTO.cs
> +    }
I suggest to add here a conversion method DTO-Object or create a mapper class for the conversion

2023-03-10 18:34 UTC, TinelValentin commented on Common/Role.cs
> +        ADMIN = 2,
what's the point to reinitialize the values if we set them based on the string we receive, not the integer value?

2023-03-10 18:52 UTC, radusalex1 commented on Controllers/UserController.cs
> +        private User ToUser(UserRegisterDTO userRegisterDTO)
So?

2023-03-12 10:55 UTC, radusalex1 commented on Controllers/UserController.cs
> +        private User ToUser(UserRegisterDTO userRegisterDTO)
where?

2023-03-12 17:36 UTC, TinelValentin approved these changes

2023-03-12 17:37 UTC, merged